### ISSUE TITLE
The container 'Maven Dependencies' references non existing library

### ISSUE THREAD

**Issue by arshadalisoomro** [jirkapinkas/java-blog-aggregator#4]
Hi Sir,
I cloned this repository from 

[java-blog-aggregator](https://github.com/jirkapinkas/java-blog-aggregator/tree/latest)

and imported into STS, after import I got error

```
Description Resource    Path    Location    Type
The container 'Maven Dependencies' references non existing library 'C:\Users\my-workstation\.m2\repository\org\apache\httpcomponents\httpclient\4.3.6\httpclient-4.3.6.jar' java-blog-aggregator        Build path  Build Path Problem
```

and 

```
Description Resource    Path    Location    Type
ArtifactTransferException: Failure to transfer org.apache.httpcomponents:httpclient:jar:4.3.6 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.httpcomponents:httpclient:jar:4.3.6 from/to central (http://repo.maven.apache.org/maven2): The operation was cancelled.    pom.xml /java-blog-aggregator   line 44 Maven Dependency Problem
Missing artifact org.apache.httpcomponents:httpclient:jar:4.3.6 pom.xml /java-blog-aggregator   line 1  Maven Dependency Problem.
```

Screenshot is

![error](https://cloud.githubusercontent.com/assets/2489546/12608746/b26b39fc-c4ff-11e5-86f4-78c65cd01421.png)

I removed 

```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.3.6</version>
</dependency>
```

and added 

```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.1</version>
</dependency> 
```

thus the issue was resolved.

Please check if it is there and my fix works?

Regards :
Arshad Ali Soomro.

**Comment by jirkapinkas** [comment]
The problem must be on your end (maybe you use Nexus or proxy or something else which delayed the JAR file and Eclipse was tired of waiting and threw this error, or you experienced temporary outage in Maven Central repository). To resolve this in Eclipse press ALT + F5 and select "Force update" and it should download the JAR file. Because it surely is in Maven Central repository: http://javalibs.com/artifact/org.apache.httpcomponents/httpclient

Btw. I'm too slow with posting updates, I'll have to fix that. A month ago I rewrote parts of this application so that now it runs on Spring Boot and templating engine is Thymeleaf instead of JSP: https://github.com/jirkapinkas/java-blog-aggregator-boot
